repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    - id: terraform_fmt
      run: cd terraform && ls -al
      shell: bash
      args:
      - --args=-write=true