repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5 # Get the latest from: https:/github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terraform_validate
    - id: terraform_tflint
    - id: terraform_wrapper_module_for_each
    - id: terraform_tfsec
    - id: terrascan