
name: ci
on:
  push:
    branches:
      - main
      - add-precommit-hooks
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: docker pre-commit image pull
        run: docker pull ghcr.io/antonbabenko/pre-commit-terraform:latest
        shell: bash
      - name: docker pre-commit run
        run:  docker run --name pre-commit-terraform ghcr.io/antonbabenko/pre-commit-terraform:latest
        shell: bash
      - name:  pre-commit
        run: cd terraform && ls -al
        shell: bash
      - name:  pre-commit
        run: pre-commit run -a
        shell: bash      
        # - name: Login to Docker Hub 
      #  uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
