name: pre-commit
 
on:
  pull_request:
  push:
    branches: [main, add-precommit-hooks]
 
jobs:
  runscript:
    name: check directory "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Call a Bash Script
        run: cd terraform && ls -al
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform format pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: terraform_fmt  --all-file

      #   shell: bash
      # - name: docker pre-commit run
      #   run:  docker run --name pre-commit-terraform ghcr.io/antonbabenko/pre-commit-terraform:latest
      #   shell: bash
      # - name:  pre-commit
      #   run: pre-commit run -a
      #   shell: bash 
        


# name: ci JKKASHDJK
# on:
#   push:
#     branches:
#       - main
#       - add-precommit-hooks
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - uses: pre-commit/action@v3.0.0
#       run: ls -al
      # - name: docker pre-commit image pull
      #   run: docker pull ghcr.io/antonbabenko/pre-commit-terraform:latest
      #   shell: bash
      # - name: install pre-commit
      #   run: git clone git@github.com:antonbabenko/pre-commit-terraform.git && cd pre-commit-terraform
      # - name:  list directory pre-commit
      #   run: ls -al
      #   shell: bash 
        # docker build -t pre-commit-terraform --build-arg INSTALL_ALL=true .
      # - name:  pre-commit
      #   run: docker image ls 
      #   shell: bash
      # - name:  pre-commit
      #   run: cd terraform && ls -al
      #   shell: bash
      # - name: docker pre-commit run
      #   run:  docker run --name pre-commit-terraform ghcr.io/antonbabenko/pre-commit-terraform:latest
      #   shell: bash
      # - name:  pre-commit
      #   run: pre-commit run -a
      #   shell: bash 
        
        
        # - name: Login to Docker Hub 
      #  uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
